### Login usuario con POST
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "enoelr87@gmail.com",
  "password": "Mn1234567*"
}

### Recuperar todos los usuarios
GET http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTE3Y2ZjYWQ1YmNkYjEzNzY0YTU0YiIsInVzZXJuYW1lIjoiZW5vZWxyODdAZ21haWwuY29tIiwiaWF0IjoxNzI5MzU0MjY3LCJleHAiOjE3MjkzNTc4Njd9.aqWyNCLkg9Ysdt6kfGPigggfbTiUituDRyB4cxbOwkA

### Recuperar un usuario por id
GET http://localhost:3000/users/67117cfcad5bcdb13764a549

### Recuperar todas los usuarios por un rol
GET http://localhost:3000/users?role=user

### Crear un usuario con POST
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Enoel",
  "last_name": "Ramírez Rodríguez",
  "username": "enoelr87@gmail.com",
  "password": "Mn1234567*",
  "active": true,
  "role": "User",
  "courses": ["1", "2", "3", "4", "5"],
  "token": "fake-jwt-token"
}

### Borrar un usuario
DELETE http://localhost:3000/users/671185735c99ad6c897cd312

### Actualizar un usuario
PATCH http://localhost:3000/users/671185735c99ad6c897cd312
Content-Type: application/json

{
  "phone": "+55489912652641"
}

### Recuperar todos los check list
GET http://localhost:3000/checkList/1/0/0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTE3Y2ZjYWQ1YmNkYjEzNzY0YTU0YiIsInVzZXJuYW1lIjoiZW5vZWxyODdAZ21haWwuY29tIiwiaWF0IjoxNzI5NDQ3MDIxLCJleHAiOjE3Mjk0NTA2MjF9.chRfgi3rxNJBNUT0Ni5-HmT6db6NT6vegL4qrg7WHlY

### Recuperar un check list por id
GET http://localhost:3000/checkList/235
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTE3Y2ZjYWQ1YmNkYjEzNzY0YTU0YiIsInVzZXJuYW1lIjoiZW5vZWxyODdAZ21haWwuY29tIiwiaWF0IjoxNzI5NDU0MjY5LCJleHAiOjE3Mjk0NTc4Njl9.PrkI1mrvZ3H1MRtRisEJj0mDwzq71InxU6vQEuyXBP4

### Recuperar todos las areas list
GET http://localhost:3000/areaList
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTE3Y2ZjYWQ1YmNkYjEzNzY0YTU0YiIsInVzZXJuYW1lIjoiZW5vZWxyODdAZ21haWwuY29tIiwiaWF0IjoxNzI5NDM5Njg3LCJleHAiOjE3Mjk0NDMyODd9.N4aee42oo0NLbyaOX-qCiQcRpXHgcQr9tcsbAlRAutI